@extends('layout')
@section('title',$scanning ? 'Flasche bestätigen' : 'Manuell hinzufügen')
@section('content')<header class="page-heading"><div><p class="eyebrow">MEINE BAR</p><h1>@yield('title')</h1></div></header>
@if($lookupMessage ?? null)<p class="notice">{{ $lookupMessage }}</p>@endif
@if($present)<section class="panel"><h2>Diese Flasche ist bereits vorhanden.</h2><p>{{ $product['name'] }} · {{ $product['barcode'] }}</p><form action="/meine-bar/{{ $product['id'] }}/entfernen" method="post">@csrf<label class="check"><input type="checkbox" name="confirmed" value="1" required> Ich möchte diese Flasche entfernen.</label><button class="primary">Entfernen bestätigen</button></form></section>@else
<form method="post" action="/meine-bar" class="panel form-stack" data-critical>@csrf
@if(!empty($product['image_path']))<img class="product-preview" src="/medien/{{ $product['image_path'] }}" alt="Produktbild" width="160" height="160">@endif
<label>Barcode<input name="barcode" inputmode="numeric" pattern="[0-9]{8,14}" value="{{ old('barcode',$product['barcode'] ?? '') }}" @readonly($scanning)></label><label>Produktname<input name="name" required maxlength="255" value="{{ old('name',$product['name'] ?? '') }}"></label><label>Marke<input name="brand" maxlength="255" value="{{ old('brand',$product['brand'] ?? '') }}"></label><label>Allgemeine Cocktailzutat<select name="ingredient_id" required><option value="">Zuordnung wählen</option>@foreach($ingredients as $ingredient)<option value="{{ $ingredient->id }}" @selected(old('ingredient_id',$product['ingredient_id'] ?? '')===$ingredient->id)>{{ $ingredient->name }}</option>@endforeach</select></label><label>Alkoholgehalt in % vol (optional)<input name="abv" type="number" min="0" max="100" step="0.1" value="{{ old('abv',$product['abv'] ?? '') }}"></label><p class="muted">Prüfe die Zuordnung und korrigiere sie bei Bedarf. Deine Angaben werden dauerhaft bevorzugt.</p><label class="check"><input name="confirmed" type="checkbox" required value="1"> Angaben geprüft – zum Barbestand hinzufügen</label><button class="primary">Flasche bestätigen</button></form>@endif
@if(!empty($product['source']))<p class="muted"><a href="https://world.openfoodfacts.org" rel="noreferrer">Open Food Facts</a> · {{ $product['license'] ?? 'Daten: ODbL; Bilder: CC BY-SA 3.0' }}</p>@endif
@endsection
