<?php

namespace App\Domain\Recipes;

final class IngredientDefinitions
{
    /** Kuratierte Ergänzungen; keine automatische Gleichsetzung ähnlicher Getränke. */
    public static function additions(): array
    {
        return [
            'Amaretto' => ['liqueur', ['amaretto', 'disaronno', 'disarono']],
            'Aperol' => ['liqueur', ['aperol']],
            'Kaffeelikör' => ['liqueur', ['coffee liqueur', 'kahlua', 'kahlúa', 'tia maria']],
            'Irish Cream' => ['liqueur', ['irish cream', 'baileys irish cream', 'baileys']],
            'Blue Curaçao' => ['liqueur', ['blue curacao', 'blue curaçao']],
            'Pfirsichlikör' => ['liqueur', ['peach schnapps', 'peach liqueur']],
            'Kokoslikör' => ['liqueur', ['coconut liqueur']],
            'Kokosrum' => ['rum', ['coconut rum', 'malibu']],
            'Crème de Cassis' => ['liqueur', ['creme de cassis', 'crème de cassis', 'blackcurrant liqueur']],
            'Holunderblütenlikör' => ['liqueur', ['elderflower liqueur', 'st germain', 'st-germain', 'st. germain']],
            'Haselnusslikör' => ['liqueur', ['hazelnut liqueur', 'frangelico']],
            'Maraschinolikör' => ['liqueur', ['maraschino liqueur', 'maraschino']],
            'Kirschlikör' => ['liqueur', ['cherry liqueur', 'cherry heering', 'cherry brandy']],
            'Aprikosenlikör' => ['liqueur', ['apricot brandy', 'apricot liqueur']],
            'Bananenlikör' => ['liqueur', ['banana liqueur', 'creme de banane']],
            'Himbeerlikör' => ['liqueur', ['raspberry liqueur', 'chambord raspberry liqueur', 'chambord']],
            'Crème de Cacao' => ['liqueur', ['creme de cacao', 'crème de cacao']],
            'Schokoladenlikör' => ['liqueur', ['chocolate liqueur', 'godiva liqueur']],
            'Grüner Minzlikör' => ['liqueur', ['green creme de menthe', 'green crème de menthe']],
            'Weisser Minzlikör' => ['liqueur', ['white creme de menthe', 'white crème de menthe']],
            'Melonenlikör' => ['liqueur', ['melon liqueur', 'midori melon liqueur', 'midori']],
            'Eierlikör' => ['liqueur', ['advocaat', 'egg liqueur']],
            'Sambuca' => ['liqueur', ['sambuca']],
            'Schwarzer Sambuca' => ['liqueur', ['black sambuca']],
            'Galliano' => ['liqueur', ['galliano']],
            'Grüne Chartreuse' => ['liqueur', ['green chartreuse']],
            'Gelbe Chartreuse' => ['liqueur', ['yellow chartreuse']],
            'Jägermeister' => ['liqueur', ['jägermeister', 'jagermeister']],
            'Fernet' => ['liqueur', ['fernet', 'fernet branca', 'fernet-branca']],
            'Brandy' => ['other', ['brandy']],
            'Cognac' => ['other', ['cognac']],
            'Cachaça' => ['other', ['cachaca', 'cachaça']],
            'Pisco' => ['other', ['pisco']],
            'Mezcal' => ['other', ['mezcal']],
            'Absinth' => ['other', ['absinthe', 'absinth']],
            'Calvados' => ['other', ['calvados']],
            'Apfelbrand' => ['other', ['apple brandy', 'applejack']],
            'Kirsch' => ['other', ['kirsch', 'kirschwasser']],
            'Bourbon' => ['whisky', ['bourbon', 'bourbon whiskey']],
            'Scotch' => ['whisky', ['scotch', 'scotch whisky', 'blended scotch']],
            'Rye Whiskey' => ['whisky', ['rye whiskey', 'rye whisky']],
            'Irischer Whiskey' => ['whisky', ['irish whiskey', 'irish whisky']],
            'Rum' => ['rum', ['rum']],
            'Goldener Rum' => ['rum', ['gold rum', 'golden rum']],
            'Gereifter Rum' => ['rum', ['aged rum', 'añejo rum', 'anejo rum']],
            'Overproof Rum' => ['rum', ['overproof rum', '151 proof rum']],
            'Gewürzrum' => ['rum', ['spiced rum']],
            'Trockener Wermut' => ['wine', ['dry vermouth', 'vermouth dry']],
            'Weisser süsser Wermut' => ['wine', ['sweet white vermouth', 'bianco vermouth', 'vermouth bianco']],
            'Prosecco' => ['wine', ['prosecco']],
            'Champagner' => ['wine', ['champagne']],
            'Schaumwein' => ['wine', ['sparkling wine', 'sekt']],
            'Weisswein' => ['wine', ['white wine']],
            'Rotwein' => ['wine', ['red wine']],
            'Portwein' => ['wine', ['port', 'port wine']],
            'Sherry' => ['wine', ['sherry']],
            'Lillet Blanc' => ['wine', ['lillet blanc']],
            'Orangenbitter' => ['bitters', ['orange bitters']],
            'Peychaud’s Bitter' => ['bitters', ["peychaud's bitters", 'peychauds bitters']],
            'Cranberrysaft' => ['juice', ['cranberry juice']],
            'Grapefruitsaft' => ['juice', ['grapefruit juice']],
            'Apfelsaft' => ['juice', ['apple juice']],
            'Tomatensaft' => ['juice', ['tomato juice']],
            'Maracujasaft' => ['juice', ['passion fruit juice', 'passionfruit juice']],
            'Traubensaft' => ['juice', ['grape juice']],
            'Kirschsaft' => ['juice', ['cherry juice']],
            'Mandelsirup' => ['syrup', ['orgeat', 'orgeat syrup', 'almond syrup']],
            'Agavensirup' => ['syrup', ['agave syrup', 'agave nectar']],
            'Honigsirup' => ['syrup', ['honey syrup']],
            'Holunderblütensirup' => ['syrup', ['elderflower syrup', 'elderflower cordial']],
            'Himbeersirup' => ['syrup', ['raspberry syrup']],
            'Vanillesirup' => ['syrup', ['vanilla syrup']],
            'Schokoladensirup' => ['syrup', ['chocolate syrup']],
            'Ginger Beer' => ['soft', ['ginger beer']],
            'Cola' => ['soft', ['cola', 'coca-cola', 'coca cola']],
            'Zitronenlimonade' => ['soft', ['lemonade', 'lemon-lime soda', 'sprite', '7-up']],
            'Kokoswasser' => ['soft', ['coconut water']],
            'Bier' => ['other', ['beer']],
            'Cider' => ['other', ['cider', 'hard cider']],
            'Alkoholfreie Gin-Alternative' => ['soft', ['non-alcoholic gin', 'alcohol-free gin']],
            'Alkoholfreie Rum-Alternative' => ['soft', ['non-alcoholic rum', 'alcohol-free rum']],
            'Alkoholfreier Aperitif' => ['soft', ['non-alcoholic aperitif', 'alcohol-free aperitif']],
            'Milch' => ['basic', ['milk']],
            'Rahm' => ['basic', ['cream', 'heavy cream', 'double cream', 'sahne']],
            'Kokosmilch' => ['basic', ['coconut milk']],
            'Cream of Coconut' => ['basic', ['cream of coconut']],
            'Kokosrahm' => ['basic', ['coconut cream']],
            'Eiweiss' => ['basic', ['egg white', 'egg whites']],
            'Eigelb' => ['basic', ['egg yolk', 'egg yolks']],
            'Ei' => ['basic', ['egg', 'eggs']],
            'Honig' => ['basic', ['honey']],
            'Brauner Zucker' => ['basic', ['brown sugar']],
            'Demerara-Zucker' => ['basic', ['demerara sugar']],
            'Zimt' => ['garnish', ['cinnamon']],
            'Ingwer' => ['garnish', ['ginger', 'fresh ginger']],
            'Erdbeeren' => ['garnish', ['strawberries', 'strawberry']],
            'Gurke' => ['garnish', ['cucumber']],
            'Apfel' => ['garnish', ['apple']],
            'Orangenschale' => ['garnish', ['orange peel', 'orange zest']],
            'Zitronenschale' => ['garnish', ['lemon peel', 'lemon zest']],
            'Cocktailkirschen' => ['garnish', ['maraschino cherry', 'maraschino cherries', 'cocktail cherry']],
            'Kaffee' => ['basic', ['coffee']],
            'Espresso' => ['basic', ['espresso']],
            'Gesüsste Kondensmilch' => ['basic', ['sweetened condensed milk', 'condensed milk']],
            'Vanilleextrakt' => ['basic', ['vanilla extract']],
            'Vanilleglace' => ['basic', ['vanilla ice cream', 'vanilla ice-cream']],
            'Kakaopulver' => ['basic', ['cocoa powder']],
        ];
    }

    public static function extraSynonyms(): array
    {
        return [
            'Minze' => ['mint leaves', 'fresh mint', 'fresh mint leaves'],
            'Limettensaft' => ['fresh lime juice', 'freshly squeezed lime juice'],
            'Zitronensaft' => ['fresh lemon juice', 'freshly squeezed lemon juice'],
            'Orangensaft' => ['fresh orange juice', 'freshly squeezed orange juice'],
            'Eis' => ['crushed ice', 'ice cube', 'eiswürfel'],
            'Wasser' => ['cold water', 'boiling water', 'hot water'],
            'Zucker' => ['white sugar', 'granulated sugar', 'caster sugar'],
            'Grenadine' => ['grenadine syrup'],
            'Gin' => ['london dry gin', 'dry gin'],
            'Whisky' => ['whisky', 'blended whiskey'],
            'Roter Wermut' => ['vermouth rosso', 'rosso vermouth'],
        ];
    }
}
