@extends('layout')
@section('title',$recipe ? 'Rezept bearbeiten' : 'Eigenes Rezept')
@section('content')
<header class="page-heading"><div><p class="eyebrow">AUS DEINER HAUSBAR</p><h1>{{ $recipe && !$recipe->household ? 'Deine Haushaltskopie' : ($recipe ? 'Rezept bearbeiten' : 'Eigenes Rezept') }}</h1></div></header>
<form method="post" action="{{ $recipe ? '/rezepte/'.$recipe->id.'/bearbeiten' : '/rezepte' }}" enctype="multipart/form-data" class="panel form-stack" data-critical>@csrf
<label>Rezeptname<input name="name" value="{{ old('name',$recipe?->name) }}" required maxlength="255"></label><div class="form-grid">
<label>Alkohol<select name="alcoholic"><option value="1" @selected(old('alcoholic',$recipe?->alcoholic ?? 1)==1)>Alkoholisch</option><option value="0" @selected(old('alcoholic',$recipe?->alcoholic ?? 1)==0)>Alkoholfrei</option></select></label>
@foreach(['base_spirit'=>'Basisspirituose','taste'=>'Geschmacksrichtung','method'=>'Zubereitungsart','glass'=>'Glas'] as $field=>$label)<label>{{ $label }}<input name="{{ $field }}" value="{{ old($field,$recipe?->$field) }}" maxlength="100"></label>@endforeach</div>
<h2>Zutaten für ein Glas</h2><div id="recipe-lines">
@foreach(old('ingredients',$lines ?: [['ingredient_id'=>'','amount'=>'','unit'=>'cl','role'=>'required']]) as $i=>$line)<div class="recipe-line"><label>Zutat<select name="ingredients[{{ $i }}][ingredient_id]" required><option value="">Zutat wählen</option>@foreach($ingredients as $ingredient)<option value="{{ $ingredient->id }}" @selected($line['ingredient_id']===$ingredient->id)>{{ $ingredient->name }}</option>@endforeach</select></label><label>Menge<input name="ingredients[{{ $i }}][amount]" type="number" min="0" max="10000" step="0.001" value="{{ $line['amount'] }}"></label><label>Einheit<select name="ingredients[{{ $i }}][unit]">@foreach(['cl','g','Stück','Prise','Spritzer'] as $unit)<option @selected(($line['unit'] ?? 'cl')===$unit)>{{ $unit }}</option>@endforeach</select></label><label>Verwendung<select name="ingredients[{{ $i }}][role]">@foreach(['required'=>'Pflicht','optional'=>'Optional','garnish'=>'Garnitur'] as $value=>$label)<option value="{{ $value }}" @selected($line['role']===$value)>{{ $label }}</option>@endforeach</select></label><button type="button" class="remove-line" aria-label="Zutat entfernen">×</button></div>@endforeach</div><button type="button" id="add-line">+ Weitere Zutat</button>
<label>Zubereitung<textarea name="instructions" rows="7" required maxlength="20000">{{ old('instructions',$recipe?->instructions) }}</textarea></label><label>Rezeptfoto (JPEG, PNG oder WebP)<input type="file" name="photo" accept="image/jpeg,image/png,image/webp"></label><p class="muted">Das Foto wird verkleinert und zugeschnitten. HEIC wird nicht unterstützt.</p><div class="actions"><button class="primary">Rezept speichern</button><a class="button" href="/entdecken">Abbrechen</a></div></form>
@endsection
