@extends('layout')
@section('title',request()->routeIs('favorites') ? 'Favoriten' : (request()->routeIs('feasible') ? 'Machbar' : 'Entdecken'))
@section('content')
<header class="page-heading"><div><p class="eyebrow">DIE REZEPTSAMMLUNG</p><h1>@yield('title')</h1><p class="muted">Finde deinen Drink – passend zu deiner Bar und deiner Stimmung.</p></div><a class="button" href="/rezepte/neu">+ Eigenes Rezept</a></header>
<form method="get" class="filters"><label class="search-label">Rezept suchen<input type="search" name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Zum Beispiel Negroni …"></label><label>Machbarkeit<select name="rank"><option value="">Alle</option>@foreach(\App\Domain\Recipes\Feasibility::LABELS as $rank=>$label)<option value="{{ $rank }}" @selected((string)($filters['rank'] ?? '')===(string)$rank)>{{ $label }}</option>@endforeach</select></label><label>Alkohol<select name="alcoholic"><option value="">Alle</option><option value="1" @selected(($filters['alcoholic'] ?? '')==='1')>Alkoholisch</option><option value="0" @selected(($filters['alcoholic'] ?? '')==='0')>Alkoholfrei</option></select></label>
@foreach(['base_spirit'=>'Basisspirituose','taste'=>'Geschmacksrichtung','method'=>'Zubereitungsart'] as $field=>$label)<label>{{ $label }}<input name="{{ $field }}" value="{{ $filters[$field] ?? '' }}" maxlength="100"></label>@endforeach
<label>Sortierung<select name="sort"><option value="rating">Beliebtheit</option><option value="name" @selected(($filters['sort'] ?? '')==='name')>Alphabetisch</option></select></label>@if(!empty($filters['hidden']))<input type="hidden" name="hidden" value="1">@endif<button class="primary">Suchen & filtern</button></form>
<p class="muted">{{ $recipes->total() }} {{ $recipes->total() === 1 ? 'Rezept' : 'Rezepte' }}{{ !empty($filters['hidden']) ? ' · Ausgeblendete Rezepte' : '' }}</p>
<div class="recipe-grid">@forelse($recipes as $recipe)@include('recipes.card')@empty<div class="empty-state"><h2>Hier ist noch Platz für einen Drink.</h2><p>Versuche andere Filter oder ergänze deinen Barbestand.</p><a class="button" href="/meine-bar">Meine Bar öffnen</a></div>@endforelse</div>
@if($recipes->hasPages())<nav class="pagination" aria-label="Ergebnisseiten">@if($recipes->previousPageUrl())<a class="button" href="{{ $recipes->previousPageUrl() }}">← Zurück</a>@endif<span>Seite {{ $recipes->currentPage() }} von {{ $recipes->lastPage() }}</span>@if($recipes->nextPageUrl())<a class="button" href="{{ $recipes->nextPageUrl() }}">Weiter →</a>@endif</nav>@endif
@endsection
