@extends('layout')
@section('title',$recipe->name)
@section('content')
<a class="back-link" href="/entdecken">← Zur Rezeptsammlung</a>
<div class="recipe-detail"><div class="detail-image"><img src="{{ $recipe->image_path ? '/medien/'.$recipe->image_path : '/assets/drink.svg' }}" alt="{{ $recipe->image_path ? $recipe->name : 'Illustration eines Cocktailglases' }}" width="600" height="600"></div><div><p class="eyebrow">{{ $recipe->household ? 'AUS DEINER HAUSBAR' : 'AUS DER REZEPTSAMMLUNG' }}</p><h1>{{ $recipe->name }}</h1><span class="badge rank-{{ $recipe->feasibility['rank'] }}">{{ $recipe->feasibility['label'] }}</span>
<div class="recipe-facts"><span>{{ $recipe->alcoholic ? 'Alkoholisch' : 'Alkoholfrei' }}</span><span>{{ $recipe->taste }}</span><span>{{ $recipe->method }}</span><span>{{ $recipe->glass }}</span><span>{{ $recipe->rating !== null ? number_format((float)$recipe->rating,1).' ★' : 'Noch unbewertet' }}</span></div>
<p class="abv">{{ $recipe->abv !== null ? number_format($recipe->abv,1,'.',"'").' % vol' : 'Alkoholgehalt nicht berechenbar' }}<small>Näherungswert ohne Eisverdünnung</small></p>
<div class="actions"><form method="post" action="/rezepte/{{ $recipe->id }}/favorit">@csrf<input type="hidden" name="present" value="{{ $favorite ? 0 : 1 }}"><button class="primary">{{ $favorite ? '♥ Favorit entfernen' : '♡ Als Favorit merken' }}</button></form><a class="button" href="/rezepte/{{ $recipe->id }}/bearbeiten">{{ $recipe->household ? 'Rezept bearbeiten' : 'Als Haushaltskopie anpassen' }}</a></div>
@if(config('privatebar.mode')==='cloud' && auth()->check())<form method="post" action="/rezepte/{{ $recipe->id }}/bewertung" class="inline-form">@csrf<label>Deine Bewertung<select name="stars">@for($s=1;$s<=5;$s++)<option value="{{ $s }}">{{ $s }} {{ $s===1 ? 'Stern' : 'Sterne' }}</option>@endfor</select></label><button>Bewerten</button></form>@endif
</div></div>
<div class="detail-columns"><section class="panel"><div class="section-heading"><h2>Zutaten</h2><span class="muted">Für ein Glas</span></div><ul class="ingredient-list">@foreach($recipe->feasibility['lines'] as $line)<li><div><strong>{{ $line['amount'] !== null ? rtrim(rtrim(number_format((float)$line['amount'],3,'.',''),'0'),'.').' '.$line['unit'] : ($line['original_measure'] ?: '') }}</strong> {{ $line['name'] }}<small class="ingredient-state">{{ $line['state'] }}{{ $line['replacement_id'] ? ' durch '.($names[$line['replacement_id']] ?? '') : '' }}{{ $line['role'] !== 'required' && $line['state']==='vorhanden' ? ' · '.($line['role']==='garnish'?'Garnitur':'optional') : '' }}</small></div>@if($line['state']==='fehlend')<form method="post" action="/einkaufsliste">@csrf<input type="hidden" name="ingredients[]" value="{{ $line['ingredient_id'] }}"><button class="small-button" aria-label="{{ $line['name'] }} zur Einkaufsliste hinzufügen">+</button></form>@endif</li>@endforeach</ul>@if($recipe->feasibility['missing'])<form method="post" action="/einkaufsliste">@csrf @foreach($recipe->feasibility['missing'] as $id)<input type="hidden" name="ingredients[]" value="{{ $id }}">@endforeach<button>Alle fehlenden Zutaten einkaufen</button></form>@endif</section>
<section class="panel"><h2>Zubereitung</h2>@if($recipe->translation_pending)<p class="badge">Übersetzung ausstehend</p>@endif<div class="instructions">{{ $recipe->instructions }}</div><h3>Quelle & Lizenz</h3>@forelse($sources as $source)<p><a href="{{ $source->url }}" rel="noreferrer">{{ $source->provider === 'cocktaildb' ? 'TheCocktailDB' : 'OpenDrinks' }}</a><small class="source-license">{{ $source->license }}</small></p>@empty<p class="muted">Eigenes Rezept der Hausbar.</p>@endforelse</section></div>
<details class="panel"><summary>Rezept verwalten</summary><form method="post" action="/rezepte/{{ $recipe->id }}/sichtbarkeit">@csrf<input type="hidden" name="hidden" value="{{ $recipe->hidden ? 0 : 1 }}"><button>{{ $recipe->hidden ? 'Wieder einblenden' : 'Für den Haushalt ausblenden' }}</button></form>@if(!$recipe->household)<form method="post" action="/rezepte/{{ $recipe->id }}/uebersetzung">@csrf<label>Deutsche Übersetzung manuell korrigieren<textarea name="instructions" required maxlength="20000" rows="6">{{ $recipe->instructions }}</textarea></label><button>Übersetzung speichern</button></form>@endif</details>
@endsection
