@extends('layout')
@section('title','Einstellungen')
@section('content')<header class="page-heading"><div><p class="eyebrow">DEINE BAR, WIE DU SIE MAGST</p><h1>Einstellungen</h1></div></header>
@if(config('privatebar.mode')==='pi')<section class="panel"><h2>Synchronisation</h2><dl class="status-list"><dt>Zustand</dt><dd>{{ $settings->get('sync_state','Noch nicht eingerichtet') }}</dd><dt>Letzter erfolgreicher Lauf</dt><dd>{{ $settings->get('sync_last_success') ? \Illuminate\Support\Carbon::parse($settings->get('sync_last_success'))->timezone('Europe/Zurich')->format('d.m.Y H:i T') : 'Noch kein erfolgreicher Abgleich' }}</dd></dl>@if($settings->get('sync_error'))<p class="error">{{ $settings->get('sync_error') }}</p>@endif<form method="post" action="/einstellungen/synchronisieren">@csrf<button>Jetzt synchronisieren</button></form></section>@endif
@if($settings->get('import_error'))<section class="panel"><h2>Rezeptimport</h2><p class="error">{{ $settings->get('import_error') }}</p></section>@endif
<form method="post" action="/einstellungen/dienste" class="panel form-stack">@csrf<h2>Externe Dienste</h2>
<p class="muted">Rezeptimport und Übersetzung laufen auf Cyon. Die Online-Produktsuche gilt für diese Instanz; gespeicherte Produktdaten bleiben auch bei deaktivierter Suche verfügbar.</p>
@foreach((config('privatebar.mode')==='cloud' ? ['recipe_import_enabled'=>'Automatischer Rezeptimport','translation_enabled'=>'Automatische Übersetzung','product_lookup_enabled'=>'Online-Produktsuche beim Barcode'] : ['product_lookup_enabled'=>'Online-Produktsuche beim Barcode']) as $key=>$label)
<input type="hidden" name="{{ $key }}" value="0"><label class="check"><input type="checkbox" name="{{ $key }}" value="1" @checked($settings->serviceEnabled($key))>{{ $label }}</label>
@endforeach
@if(config('privatebar.mode')==='cloud')
@if(!config('privatebar.cocktaildb_key'))<p class="muted">Der Zugang für TheCocktailDB ist noch nicht eingerichtet.</p>@endif
@if(!config('privatebar.azure_key'))<p class="muted">Der Zugang für Azure Translator ist noch nicht eingerichtet.</p>@endif
@endif
<button class="primary">Externe Dienste speichern</button></form>
<form method="post" action="/einstellungen/gemeinsam" class="panel form-stack">@csrf<h2>Gemeinsame Einstellungen</h2><div class="form-grid"><label>Importstunde (Europe/Zurich)<input name="import_hour" type="number" min="0" max="23" required value="{{ $settings->get('import_hour',4,false) }}"></label><label>Importintervall in Stunden<input name="import_frequency_hours" type="number" min="1" max="168" required value="{{ $settings->get('import_frequency_hours',24,false) }}"></label></div><fieldset><legend>Automatisch vorhandene Grundzutaten</legend><div class="checkbox-grid">@foreach($ingredients as $ingredient)<label class="check"><input type="checkbox" name="automatic[]" value="{{ $ingredient->id }}" @checked($ingredient->automatic)>{{ $ingredient->name }}</label>@endforeach</div></fieldset><button class="primary">Gemeinsame Einstellungen speichern</button></form>
<section class="panel"><h2>Gerichtete Ersatzzutaten</h2><p class="muted">Die Ersatzzutat erfüllt die benötigte Zutat. Die Gegenrichtung braucht eine eigene Regel.</p>@foreach($substitutions as $sub)<form method="post" action="/einstellungen/ersatz" class="inline-form">@csrf<input type="hidden" name="required_id" value="{{ $sub->required_id }}"><input type="hidden" name="replacement_id" value="{{ $sub->replacement_id }}"><span>{{ $ingredients->firstWhere('id',$sub->required_id)?->name }} ← {{ $ingredients->firstWhere('id',$sub->replacement_id)?->name }}</span><input type="hidden" name="enabled" value="{{ $sub->enabled ? 0 : 1 }}"><button>{{ $sub->enabled ? 'Deaktivieren' : 'Aktivieren' }}</button></form>@endforeach
<form method="post" action="/einstellungen/ersatz" class="form-grid">@csrf @foreach(['required_id'=>'Benötigte Zutat','replacement_id'=>'Ersatzzutat'] as $field=>$label)<label>{{ $label }}<select name="{{ $field }}">@foreach($ingredients as $ingredient)<option value="{{ $ingredient->id }}">{{ $ingredient->name }}</option>@endforeach</select></label>@endforeach<input type="hidden" name="enabled" value="1"><button>Ersatzregel hinzufügen</button></form></section>
<section class="panel"><h2>Verwaltung</h2><p><a class="button" href="/einstellungen/zutaten">Cocktailzutaten & Synonyme</a></p><div class="actions"><a class="button" href="/entdecken?hidden=1">Ausgeblendete Rezepte</a>@if(config('privatebar.mode')==='cloud')<a class="button" href="/einstellungen/mitglieder">Mitglieder & Einladungen</a>@else @if(in_array(request()->server('REMOTE_ADDR'),['127.0.0.1','::1']))<a class="button" href="/einstellungen/lokal">Lokale Einstellungen öffnen</a>@else<p class="muted">Lokale Systemeinstellungen sind direkt am Raspberry Pi erreichbar.</p>@endif @endif</div></section>
@if(config('privatebar.mode')==='pi')<section class="panel"><h2>Lokales System</h2>@foreach(['photo_error'=>'Fotorahmen','smb_test_result'=>'SMB-Verbindung','cloud_connection_result'=>'Pi–Cyon-Verbindung','update_state'=>'Update','update_error'=>'Updatefehler'] as $key=>$label)@if($settings->get($key))<p><strong>{{ $label }}:</strong> {{ $settings->get($key) }}</p>@endif @endforeach<p class="muted">PrivateBar {{ config('privatebar.version') }}</p></section>@endif
@if(config('privatebar.mode')==='cloud')
<form method="post" action="/einstellungen/datenbank/export" class="panel form-stack" data-critical>@csrf<h2>Datenbank exportieren</h2>
<p>Speichere die Datenbank als SQL-Datei für eine Neuinstallation. Enthalten sind Rezepte, Bestand, Einkaufslisten, Bewertungen, Einstellungen und Konten. Nach dem Einspielen startet die Anwendung im Wartungsmodus; danach ist eine neue Anmeldung nötig.</p>
<p class="muted">Die Datei enthält persönliche Daten und Passwort-Hashes. Bewahre sie geschützt auf. Bilder und die Umgebungskonfiguration müssen separat gesichert werden.</p>
<label>Dein aktuelles Passwort<input type="password" name="password" required autocomplete="current-password" maxlength="1024"></label>
<button class="primary">Datenbankexport herunterladen</button></form>
@endif
@endsection
